### ISSUE TITLE
confusion around example_dnn_nsga2 configuration

### ISSUE THREAD

**Issue by Antymon** [sferes2/nn2#7]
Hi,

In the mentioned example there are parameters controlling the number of neurons and connections set (such as `min_nb_neurons` etc). Unfortunately, after reading implementation I conclude they seem to have no impact under `dnn::ff` and control flow never uses them. Am I missing something here or is this just a mistake? If latter, same confusion is propagated through tests.

As a side question, are those parameters only meant for initialization ranges? That is, they don't really limit the number of neurons or connections through evolution if add/del rates are non-zero?

**Comment by jbmouret** [comment]
This is old (sorry), but for the record, `min_nb_neurons`, etc. are used only for initialization and not used in feed-forward mode (`dnn:ff`). They are not hard limits for evolution.
